# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c',",om
# ********************************************************************
import os

Import('env')

sources=[
    'port/lv_port_disp.c',
    # "port/lv_port_fs.c',",
    'port/lv_port_indev.c',
]
sources+= Glob('src/core/*.c')
sources+= Glob('src/draw/*.c')
sources+= Glob('src/font/*.c')
sources+= Glob('src/gpu/*.c')
sources+= Glob('src/hal/*.c')
sources+= Glob('src/misc/*.c')
sources+= Glob('src/widgets/*.c')
sources+= Glob('src/extra/*.c')
sources+= Glob('src/extra/**/*.c')
sources+= Glob('src/extra/**/**/*.c')

env.Library('lvgl', sources+[
    '../libjpeg/libjpeg.a',
    '../libgui/libgui.a',
    '../../libs/libc/libc.a',
    ],
    CFLAGS='$CFLAGS -DLV_CONF_INCLUDE_SIMPLE  -Iapp/liblvgl/ -Ilibs/include/c/ -Iapp/libgui/ -Iapp/libjpeg/',)
