# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


env = env.Clone(
  w=GetOption('w'),
  ENV = os.environ,
  PATH= [os.environ['PATH'],'/opt/local/bin' ],
  )


source=[ 
]

source+= Glob('*.c')

libs=[
    'liblvgl.a',
    'libgui.a',
    'libimage.a',
    'libpng.a',
]

libpath=[
 
]
include=[
    '.',
    'xtrack/Pages',
    'xtrack/Pages/Config',
    'xtrack/Pages/Resource',
    'xtrack/'
]+libpath


cflags='  -DLV_LVGL_H_INCLUDE_SIMPLE=1 '

env.Program('track', source,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=env.get('LIBPATH')+libpath,
    CPPPATH=env.get('CPPPATH')+include,

    CFLAGS='$CFLAGS $LIBCFLAGS '+cflags,
    LINKFLAGS= '$LINKFLAGS $USER')

