# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

source=[]

source+=Glob('*.c')

env.Library('jpeg', source+env['LIBC'],CFLAGS='$CFLAGS $LIBCFLAGS -Iapp/libjpeg/')
