# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c",om
# ********************************************************************
import os

Import('env')

type='a6le'
cflags=''

if env['ARCHTYPE']=='arm':
    type='arm32le'
    cflags ='-DINLINES -DGC_MACROS -DARMV6 -DMB_LEN_MAX=8 -D_LARGEFILE64_SOURCE -DHAVE_HIDDEN'
else:
    print('libchez not support',env['ARCHTYPE'])

source=[]
source+= ['c/statics.c',
         'c/segment.c',
         'c/alloc.c', 
         'c/symbol.c', 
         'c/intern.c', 
         'c/gcwrapper.c', 
        'c/number.c',
         'c/schsig.c', 
         'c/io.c',
        'c/new-io.c',
        'c/print.c',
        'c/fasl.c',
        'c/stats.c',
        'c/foreign.c',
        'c/prim.c',
        'c/prim5.c',
        'c/flushcache.c',
        'c/schlib.c', 
        'c/thread.c',
        # 'c/expeditor.c',
        'c/scheme.c', 
        'c/gc.c',
        'c/gc-ocd.c', 
        'c/gc-oce.c',
        'c/gc-011.c', 
        'c/arm32le.c',
        'c/compress-io.c'
]
source+= Glob(type+'/*.h')



if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


env.Library('chez', source+[
        '../libzlib/libzlib.a',
        '../liblz4/liblz4.a',
        '../libuuid/libuuid.a',
]+env['LIBC'],CFLAGS='$CFLAGS $LIBCFLAGS -Iapp/libuuid -Iapp/liblz4/lib -Iapp/libzlib -Iapp/libchez/'+type+' -I. '+cflags )