# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')



source= [
    'main.c',
    '../libsdl2/libsdl2.a',  
    '../libgui/libgui.a',
    '../libgui/libimage.a',
    '../libjpeg/libjpeg.a',
    '../libpng/libpng.a',
    '../libzlib/libzlib.a',
    ]+env['LIBC']
    
if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


env.Program('sdl2', source,
    CFLAGS='$CFLAGS $LIBCFLAGS -Iapp/libsdl2/ -Iapp/libsdl2/include',
    LINKFLAGS= '$LINKFLAGS $USER')


source= [
    'player.c',

    '../libsdl2/libsdl2.a', 
    '../libgui/libgui.a', 
    '../libffmpeg/libavdevice/libavdevice.a',
    '../libffmpeg/libavfilter/libavfilter.a',
    '../libffmpeg/libavformat/libavformat.a', 
    '../libffmpeg/libswscale/libswscale.a', 
    '../libffmpeg/libavcodec/libavcodec.a',  
    '../libffmpeg/libavutil/libavutil.a',

    ]+env['LIBC']
    
if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Program('player', source,
    CFLAGS='$CFLAGS $LIBCFLAGS  -Iapp/libsdl2/ -Iapp/libsdl2/include -Iapp/libffmpeg/',
    LINKFLAGS= '$LINKFLAGS $USER')



#showimage

source= [
    'showimage.c',

    '../libsdl2/libsdl2.a',   
    '../libsdl2-image/libsdl2-image.a',
    '../libgui/libgui.a',
    '../libjpeg/libjpeg.a',
    '../libpng/libpng.a',
    '../libzlib/libzlib.a',
    '../libwebp/libwebp.a',
    
    ]+env['LIBC']
    
if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Program('showimage', source,
    CFLAGS='$CFLAGS $LIBCFLAGS  -Iapp/libsdl2/ -Iapp/libjpeg/ -Iapp/libpng/ -Iapp/libsdl2/include -Iapp/libsdl2-image/',
    LINKFLAGS= '$LINKFLAGS $USER')
