# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


source = [
    'main.c',

]

libs = [
    'libsdl2.a',
    'libgui.a',
    'libimage.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
]

libpath = [
    '../../eggs/libsdl2/',
]

env.Program('sdl2', source,
            LIBS=libs+env.get('LIBS'),
            LIBPATH=env.get('LIBPATH')+libpath,
            CFLAGS='$CFLAGS $LIBCFLAGS ',
            LINKFLAGS='$LINKFLAGS $USER')


source = [
    'player.c',



]

libpath = [
    '../../eggs/libsdl2/',
    '../../eggs/libffmpeg/libavdevice/',
    '../../eggs/libffmpeg/libavfilter/',
    '../../eggs/libffmpeg/libavformat/',
    '../../eggs/libffmpeg/libswscale/',
    '../../eggs/libffmpeg/libavcodec/',
    '../../eggs/libffmpeg/libavutil/',
]
libs = [
    'libsdl2.a',
    'libgui.a',
    'libavdevice.a',
    'libavfilter.a',
    'libavformat.a',
    'libswscale.a',
    'libavcodec.a',
    'libavutil.a',
]

include = [
    '../../eggs/libffmpeg/',
]

env.Program('player', source,
            LIBS=libs+env.get('LIBS'),
            LIBPATH=env.get('LIBPATH')+libpath,
            CPPPATH=env.get('CPPPATH')+include,
            CFLAGS='$CFLAGS $LIBCFLAGS -DHAVE_CBRT -DHAVE_ERF -DHAVE_HYPOT -DHAVE_TRUNC -DHAVE_RINT',
            LINKFLAGS='$LINKFLAGS $USER')


# showimage

source = [
    'showimage.c',


]
libs = [

    'libsdl2.a',
    'libsdl2-image.a',
    'libgui.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
    'libwebp.a',
]
include = [
    '../../eggs/libsdl2-image/',
]

libpath = [
    '../../eggs/libsdl2/',
    '../../eggs/libsdl2-image/',
    '../../eggs/libwebp/',

    '../../eggs/libffmpeg/libavdevice/',
    '../../eggs/libffmpeg/libavfilter/',
    '../../eggs/libffmpeg/libavformat/',
    '../../eggs/libffmpeg/libswscale/',
    '../../eggs/libffmpeg/libavcodec/',
    '../../eggs/libffmpeg/libavutil/',
]

env.Program('showimage', source,
            LIBS=libs+env.get('LIBS'),
            LIBPATH=env.get('LIBPATH')+libpath,
            CPPPATH=env.get('CPPPATH')+include,
            CFLAGS='$CFLAGS $LIBCFLAGS ',
            LINKFLAGS='$LINKFLAGS $USER')


# showfont

source = [
    'showfont.c',
]

libs = [
    'libsdl2.a',
    'libsdl2-image.a',
    'libsdl2-ttf.a',
    'libfreetype.a',
    'libgui.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
    'libwebp.a',
]

include = [
    '../../eggs/libsdl2-image/',
    '../../eggs/libsdl2-ttf/',
    '../../eggs/libfreetype/include',

]

libpath = [
    '../../eggs/libsdl2/',
    '../../eggs/libsdl2-image/',
    '../../eggs/libsdl2-ttf/',
    '../../eggs/libfreetype',

    '../../eggs/libwebp/',

    '../../eggs/libffmpeg/libavdevice/',
    '../../eggs/libffmpeg/libavfilter/',
    '../../eggs/libffmpeg/libavformat/',
    '../../eggs/libffmpeg/libswscale/',
    '../../eggs/libffmpeg/libavcodec/',
    '../../eggs/libffmpeg/libavutil/',
]

# -Iapp/libsdl2/ -Iapp/libjpeg/ -Iapp/libpng/ -Iapp/libsdl2-ttf/ -Iapp/libsdl2/include -Iapp/libfreetype/include -Iapp/libsdl2-image/
env.Program('showfont', source,
            LIBS=libs+env.get('LIBS'),
            LIBPATH=env.get('LIBPATH')+libpath,
            CPPPATH=env.get('CPPPATH')+include,
            CFLAGS='$CFLAGS $LIBCFLAGS  ',
            LINKFLAGS='$LINKFLAGS $USER')
