# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os
import platform 
plt = platform.system()

Import('env')

env = env.Clone(
  w=GetOption('w'),
  ENV = os.environ,
  PATH= [os.environ['PATH'],'/opt/local/bin' ],
  )

env.Library('jpeg', [
    "jdinput.c",
    "jdhuff.c",
    "jddctmgr.c",
    "jdcolor.c",
    "jdcoefct.c",
    "jdapistd.c",
    "jcomapi.c",
    "jutils.c",
    "jquant2.c",
    "jquant1.c",
    "jmemmgr.c",
    "jidctred.c",
    "jidctint.c",
    "jidctfst.c",
    "jidctflt.c",
    "jfdctint.c",
    "jfdctfst.c",
    "jfdctflt.c",
    "jerror.c",
    "jdtrans.c",
    "jdsample.c",
    "jdpostct.c",
    "jdphuff.c",
    "jdmerge.c",
    "jdmaster.c",
    "jdmarker.c",
    "jdmainct.c",
    "jdapimin.c",
    "jmemsysextern.c",
    '../../libs/libc/libc.a',
],CFLAGS='$CFLAGS -Ilibs/include/c/')


# env.Program('jpeg.elf', [
#     'libjpeg.a',
#     '../../libs/libc/libc.a',
#     ],
#     CFLAGS='$CFLAGS -Ilibs/include/c/ ',
#     LINKFLAGS= '$LINKFLAGS --entry main -Tuser.ld')