# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')               


arch_type=env.get('ARCHTYPE')

if arch_type in 'arm':
    boot=SConscript(dirs=['arm'], exports='env')
elif arch_type in 'xtensa':
    boot=SConscript(dirs=['xtensa'], exports='env')
else:
    boot=SConscript(dirs=[arch_type], exports='env')