# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c',",om
# ********************************************************************
import os

Import('env')

source=[]

source+= [
    'postprocess.c'
]



include = [
    '../',
    '../../include/c',
    '../../include/'
]


env.Library('postproc', source,
    CPPPATH=env.get('CPPPATH')+include,

    CFLAGS='$CFLAGS  $LIBCFLAGS -Iapp/libffmpeg/ ',)
