# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

env.Library('algorithm', 
    [
    'circle_queue.c',
    'pool.c',
    'queue_pool.c',
    ],CFLAGS='$CFLAGS -I. -Ilibs/include/algorithm -Ilibs/include/kernel')