# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c",",om
# ********************************************************************
import os

Import('env')


env.Library('zlib', [
   "adler32.c",
    "compress.c",
    "crc32.c",
    "deflate.c",
    "gzclose.c",
    "gzlib.c",
    "gzread.c",
    "gzwrite.c",
    "infback.c",
    "inffast.c",
    "inflate.c",
    "inftrees.c",
    "trees.c",
    "uncompr.c",
    "zutil.c",
    '../../libs/libc/libc.a',
],CFLAGS='$CFLAGS -Ilibs/include/c/')


# env.Program('jpeg.elf', [
#     'libjpeg.a',
#     '../../libs/libc/libc.a',
#     ],
#     CFLAGS='$CFLAGS -Ilibs/include/c/ ',
#     LINKFLAGS= '$LINKFLAGS --entry main -Tuser.ld')