# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c',",om
# ********************************************************************
import os

Import('env')

source=[]

source+=[
    'audioconvert.c',    
    'dither.c',          
    'options.c',         
    'rematrix.c',        
    'resample.c',        
    'resample_dsp.c',    
    'swresample.c',      
    'swresample_frame.c',
]

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


source+= [
    ]+env['LIBC']

env.Library('swresample', source,
    CFLAGS='$CFLAGS  $LIBCFLAGS -Iapp/libffmpeg/ ',)
