# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c",om
# ********************************************************************
import os

Import('env')

cflags=''


source=[]
source+= [
    'lib/lz4.c',
    'lib/lz4frame.c',
    'lib/lz4hc.c',
    'lib/xxhash.c'
]


if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


env.Library('lz4', source+[
]+env['LIBC'],CFLAGS='$CFLAGS $LIBCFLAGS -Iapp/libzlib -Iapp/liblz4 -Iapp/liblz4/lib -I. '+cflags )