#ifndef _ETK_KEY_H
#define _ETK_KEY_H



typedef enum EtkKey_e{

	//ETK_KEY_BS			 =0x08,
	//ETK_KEY_CR			 =	0x0d,
	//ETK_KEY_ESC			 =	0x01b,

	ETK_KEY_SPACE         =  0x020,
	ETK_KEY_EXCLAM        =  0x021,
	ETK_KEY_QUOTEDBL      =  0x022,
	ETK_KEY_NUMBERSIGN    =  0x023,
	ETK_KEY_DOLLAR        =  0x024,
	ETK_KEY_PERCENT       =  0x025,
	ETK_KEY_AMPERSAND     =  0x026,
	ETK_KEY_APOSTROPHE    =  0x027,
	ETK_KEY_QUOTERIGHT    =  0x027,
	ETK_KEY_PARENLEFT     =  0x028,
	ETK_KEY_PARENRIGHT    =  0x029,
	ETK_KEY_ASTERISK      =  0x02a,
	ETK_KEY_PLUS          =  0x02b,
	ETK_KEY_COMMA         =  0x02c,
	ETK_KEY_MINUS         =  0x02d,
	ETK_KEY_PERIOD        =  0x02e,
	ETK_KEY_SLASH         =  0x02f,
	ETK_KEY_0             =  0x030,
	ETK_KEY_1             =  0x031,
	ETK_KEY_2             =  0x032,
	ETK_KEY_3             =  0x033,
	ETK_KEY_4             =  0x034,
	ETK_KEY_5             =  0x035,
	ETK_KEY_6             =  0x036,
	ETK_KEY_7             =  0x037,
	ETK_KEY_8             =  0x038,
	ETK_KEY_9             =  0x039,
	ETK_KEY_COLON         =  0x03a,
	ETK_KEY_SEMICOLON     =  0x03b,
	ETK_KEY_LESS          =  0x03c,
	ETK_KEY_EQUAL         =  0x03d,
	ETK_KEY_GREATER       =  0x03e,
	ETK_KEY_QUESTION      =  0x03f,
	ETK_KEY_AT            =  0X040,
	ETK_KEY_A             =  0x041,
	ETK_KEY_B             =  0x042,
	ETK_KEY_C             =  0x043,
	ETK_KEY_D             =  0x044,
	ETK_KEY_E             =  0x045,
	ETK_KEY_F             =  0x046,
	ETK_KEY_G             =  0x047,
	ETK_KEY_H             =  0x048,
	ETK_KEY_I             =  0x049,
	ETK_KEY_J             =  0x04a,
	ETK_KEY_K             =  0x04b,
	ETK_KEY_L             =  0x04c,
	ETK_KEY_M             =  0x04d,
	ETK_KEY_N             =  0x04e,
	ETK_KEY_O             =  0x04f,
	ETK_KEY_P             =  0x050,
	ETK_KEY_Q             =  0x051,
	ETK_KEY_R             =  0x052,
	ETK_KEY_S             =  0x053,
	ETK_KEY_T             =  0x054,
	ETK_KEY_U             =  0x055,
	ETK_KEY_V             =  0x056,
	ETK_KEY_W             =  0x057,
	ETK_KEY_X             =  0x058,
	ETK_KEY_Y             =  0x059,
	ETK_KEY_Z             =  0x05a,
	ETK_KEY_BRACKETLEFT   =  0x05b,
	ETK_KEY_BACKSLASH     =  0x05c,
	ETK_KEY_BRACKETRIGHT  =  0x05d,
	ETK_KEY_ASCIICIRCUM   =  0x05e,
	ETK_KEY_UNDERSCORE    =  0x05f,
	ETK_KEY_QUOTELEFT     =  0x060,
	ETK_KEY_GRAVE         =  0x060,
	ETK_KEY_a             =  0x061,
	ETK_KEY_b             =  0x062,
	ETK_KEY_c             =  0x063,
	ETK_KEY_d             =  0x064,
	ETK_KEY_e             =  0x065,
	ETK_KEY_f             =  0x066,
	ETK_KEY_g             =  0x067,
	ETK_KEY_h             =  0x068,
	ETK_KEY_i             =  0x069,
	ETK_KEY_j             =  0x06a,
	ETK_KEY_k             =  0x06b,
	ETK_KEY_l             =  0x06c,
	ETK_KEY_m             =  0x06d,
	ETK_KEY_n             =  0x06e,
	ETK_KEY_o             =  0x06f,
	ETK_KEY_p             =  0x070,
	ETK_KEY_q             =  0x071,
	ETK_KEY_r             =  0x072,
	ETK_KEY_s             =  0x073,
	ETK_KEY_t             =  0x074,
	ETK_KEY_u             =  0x075,
	ETK_KEY_v             =  0x076,
	ETK_KEY_w             =  0x077,
	ETK_KEY_x             =  0x078,
	ETK_KEY_y             =  0x079,
	ETK_KEY_z             =  0x07a,
	ETK_KEY_LEFTBRACE     =  0x07B,
	ETK_KEY_OR            =  0x07C,
	ETK_KEY_RIGHTBRACE    =  0x07D,
	ETK_KEY_NOT           =  0x07E,
	ETK_KEY_DOT           =  '.',
	ETK_KEY_HOME          =  0xFF50,
	ETK_KEY_LEFT          =  0xFF51,
	ETK_KEY_UP            =  0xFF52,
	ETK_KEY_RIGHT         =  0xFF53,
	ETK_KEY_DOWN          =  0xFF54,
	ETK_KEY_PRIOR         =  0xFF55,
	ETK_KEY_PAGEUP        =  0xFF55,
	ETK_KEY_NEXT          =  0xFF56,
	ETK_KEY_PAGEDOWN      =  0xFF56,
	ETK_KEY_END           =  0xFF57,
	ETK_KEY_BEGIN         =  0xFF58,
	ETK_KEY_INSERT        =  0xFF63,
	ETK_KEY_ENTER         =  0xFF0D,
	ETK_KEY_TAB           =  0xFF09,
	ETK_KEY_ESC           =  0xFF1B,
	ETK_KEY_RIGHTCTRL   =  0xFFE4,
	ETK_KEY_LEFTCTRL    =  0xFFE3,
	ETK_KEY_RIGHTALT    =  0xFFEA,
	ETK_KEY_LEFTALT     =  0xFFE9,
	ETK_KEY_RIGHTSHIFT  =  0xFFE2,
	ETK_KEY_LEFTSHIFT   =  0xFFE1,
	ETK_KEY_DELETE      =  0xFFFF,
	ETK_KEY_F1          =  0xFFBE,
	ETK_KEY_F2          =  0xFFBF,
	ETK_KEY_F3          =  0xFFC0,
	ETK_KEY_RETURN      = ETK_KEY_F3,
	ETK_KEY_F4          =  0xFFC1,
	ETK_KEY_F5          =  0xFFC2,
	ETK_KEY_F6          =  0xFFC3,
	ETK_KEY_F7          =  0xFFC4,
	ETK_KEY_F8          =  0xFFC5,
	ETK_KEY_F9          =  0xFFC6,
	ETK_KEY_F10         =  0xFFC7,
	ETK_KEY_CAPSLOCK    =  0xFFE5,
	ETK_KEY_BACKSPACE   =  0xFF08,
	ETK_KEY_SEND        =  0xFFA1,
	ETK_KEY_REPLY       =  0xFFA2,
	ETK_KEY_SAVE        =  0xFFA3,
	ETK_KEY_BATTERY     =  0xFFA4,
	ETK_KEY_BLUETOOTH   =  0xFFA5,
	ETK_KEY_WLAN        =  0xFFA6,
	ETK_KEY_POWER       =  0xFFA7,
	ETK_KEY_MENU        = ETK_KEY_F2,
	ETK_KEY_CHOOSE_IME  = ETK_KEY_F4
}EtkKey;

#define ETK_IS_DIGIT(key) ((key) >= ETK_KEY_0 && (key) <= ETK_KEY_9)
#define ETK_IS_ALPHA(key) ((key) >= ETK_KEY_A && (key) <= ETK_KEY_Z) && ((key) >= ETK_KEY_a && (key) <= ETK_KEY_z)
#define ETK_IS_ACTIVE_KEY(key) ((key) == ETK_KEY_ENTER || (key) == ETK_KEY_SPACE)


#endif
