# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


source=[
    'main.c',
    'etk_app.c',
    'sinclock.c',
    'mine.c',
    'terminal.c',
    'light.c',
    'power.c',
    'temhum.c',
    'status.c',
    '../libetk/libetk.a',
    '../libjpeg/libjpeg.a',
    '../libgui/libgui.a',
    '../../libs/libc/libc.a',
    ]

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


env.Program('etk.elf', source,
    CFLAGS='$CFLAGS -Ilibs/include/c/ -Iapp/libgui/ -Iapp/libjpeg/ -Iapp/libetk/',
    LINKFLAGS= '$LINKFLAGS $USER')

# env.Objcopy('etk.elf','etk',OBJCOPYFLAGS='-S')
# env.Objcopy('etk.dbg','etk',OBJCOPYFLAGS='--only-keep-debug')


