# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os
import platform 
plt = platform.system()

Import('env')

env.Program('etk.elf', [
    'main.c',
    'etk_app.c',
    'sinclock.c',
    'mine.c',
    'terminal.c',
    '../libetk/libetk.a',
    '../libjpeg/libjpeg.a',
    '../libgui/libgui.a',
    '../../libs/libc/libc.a',

    ],
    CFLAGS='$CFLAGS -Ilibs/include/c/ -Iapp/libgui/ -Iapp/libjpeg/ -Iapp/libetk/',
    LINKFLAGS= '$LINKFLAGS --entry main -Tuser.ld')

# env.Objcopy('etk.elf','etk',OBJCOPYFLAGS='-S')
# env.Objcopy('etk.dbg','etk',OBJCOPYFLAGS='--only-keep-debug')


