# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


source = []
source += Glob('src/*.c')
source += Glob('sys/sdl2/*.c')
source += Glob('lib/gz/*.c')
source += Glob('lib/xz/*.c')
source += Glob('sys/yiyiya/*.c')

source += [


]
libs = [
    'libsdl2.a',
    'libgui.a',
    'libimage.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
]

include = [
    '../../eggs/libsdl2-image/',
    '../../eggs/libsdl2-ttf/',
    '../../eggs/libjpeg/',
    '../../eggs/libfreetype/include',
    '../../eggs/libzlib',

    'include',
    '.',
    'sys/sdl2/'
]

libpath = [
    '../../eggs/libsdl2/',
    '../../eggs/libsdl2-image/',
    '../../eggs/libsdl2-ttf/',
    '../../eggs/libfreetype',

    '../../eggs/libwebp/',

]

env.Program('gnuboy', source,
            LIBS=libs+env.get('LIBS'),
            LIBPATH=env.get('LIBPATH')+libpath,
            CPPPATH=env.get('CPPPATH')+include,
            CFLAGS='$CFLAGS $LIBCFLAGS ',
            LINKFLAGS='$LINKFLAGS $USER')
