# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


source=[]
source+=Glob('src/*.c')
source+=Glob('sys/sdl2/*.c')
source+=Glob('lib/gz/*.c')
source+=Glob('lib/xz/*.c')
source+=Glob('sys/yiyiya/*.c')

source +=[
    
    '../libsdl2/libsdl2.a',  
    '../libgui/libgui.a',
    '../libgui/libimage.a',
    '../libjpeg/libjpeg.a',
    '../libpng/libpng.a',
    '../libzlib/libzlib.a',
    ]+env['LIBC']

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Program('gnuboy', source,
    CFLAGS='$CFLAGS $LIBCFLAGS -Iapp/libgui/ -Iapp/libsdl2/ -Iapp/libsdl2/include -Iapp/libjpeg -Iapp/gnuboy/include -Iapp/gnuboy/ -Iapp/gnuboy/sys/sdl2/ -I.',
    LINKFLAGS= '$LINKFLAGS $USER')