# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c",om
# ********************************************************************
import os

Import('env')


source=[]
source+= Glob('src/*.c')

env.Library('lua', source+[
    # '../libmusl/lib/libm.a',
    # '/opt/local/lib/gcc/arm-none-eabi/9.2.0/libgcc.a'
]+env['LIBC'],CFLAGS='$CFLAGS $LIBCFLAGS -Iapp/liblua/src/ -I.')