# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c',",om
# ********************************************************************
import os

Import('env')

cflags=''


source=[]
source+= [
    'uuid/compare.c',
    'uuid/gen_uuid.c',
    'uuid/isnull.c',
	'uuid/parse.c',
    'uuid/unpack.c',
    'uuid/clear.c',
    'uuid/copy.c',
	'uuid/pack.c',
    'uuid/unparse.c',
    'uuid/uuid_time.c',
]


if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


env.Library('uuid', source+[
]+env['LIBC'],CFLAGS='$CFLAGS $LIBCFLAGS -Iapp/libzlib -Iapp/libuuid  -I. '+cflags )