# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os
import platform 
plt = platform.system()

Import('env')

env = env.Clone(
  w=GetOption('w'),
  ENV = os.environ,
  PATH= [os.environ['PATH'],'/opt/local/bin' ],
  )

env.Program('microui.elf', [
    'main.c',
    'microui.c',
    'renderer.c',
    '../../app/gui/libgui.a',
    '../../libs/libc/libc.a',

    ],
    CFLAGS='$CFLAGS -Ilibs/include/c/ -Iapp/gui/',
    LINKFLAGS= '$LINKFLAGS --entry main -Tuser.ld')

# env.Objcopy('microui.elf','microui',OBJCOPYFLAGS='-S')
# env.Objcopy('microui.dbg','microui.elf',OBJCOPYFLAGS='--only-keep-debug')


