# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

env = env.Clone(
  w=GetOption('w'),
  ENV = os.environ,
  PATH= [os.environ['PATH'],'/opt/local/bin' ],
  )

source= [
    'main.c',
    'microui.c',
    'renderer.c',
    '../libgui/libgui.a',
    '../../libs/libc/libc.a',
    ]

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


env.Program('microui.elf',source,
    CFLAGS='$CFLAGS -Ilibs/include/c/ -Iapp/libgui/',
    LINKFLAGS= '$LINKFLAGS $USER')

# env.Objcopy('microui.elf','microui',OBJCOPYFLAGS='-S')
# env.Objcopy('microui.dbg','microui.elf',OBJCOPYFLAGS='--only-keep-debug')


