# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


env = env.Clone(
  w=GetOption('w'),
  ENV = os.environ,
  PATH= [os.environ['PATH'],'/opt/local/bin' ],
  )

source=[
    'ls.c',
    ]+env['LIBC']

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Program('ls', source,
    CFLAGS='$CFLAGS $LIBCFLAGS ',
    LINKFLAGS= '$LINKFLAGS $USER')


source=[
    'echo.c',
    ]+env['LIBC']

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Program('echo', source,
    CFLAGS='$CFLAGS $LIBCFLAGS ',
    LINKFLAGS= '$LINKFLAGS $USER')



source=[
    'cat.c',
    ]+env['LIBC']

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Program('cat', source,
    CFLAGS='$CFLAGS $LIBCFLAGS ',
    LINKFLAGS= '$LINKFLAGS $USER')