# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


env.Library('yiyiya', [
    'kernel.c',
    'thread.c',
    'schedule.c',
    'syscall.c',
    'exceptions.c',
    'memory.c',
    'module.c',
    'device.c',
    'vfs.c',
    'syscallfn.c',
    'devcallfn.c',
    '../arch/libarch.a',
    '../libs/libkernel/libkernel.a',
    ]
    )


