# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

env.Library('c', [
    'string.c',
    'malloc.c',
    'vsprintf.c',
    'stdio.c',
    'stdlib.c',
    'syscall.c',
    'errno.c',
    'ctype.c',
    'support.c',
    'unistd.c',
    'fcntl.c',
    'setjmp.c',
    'yiyiya.c',
    'time.c',
    'signal.c',
    'timeb.c',
    'strings.c',
    'gettimeofday.c',
    'getopt.c',
],CFLAGS='$CFLAGS -Ilibs/include/c/')