# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

source=[
    'string.c',
    'malloc.c',
    'vsprintf.c',
    'stdio.c',
    'stdlib.c',
    'syscall.c',
    'errno.c',
    'ctype.c',
    'support.c',
    'unistd.c',
    'fcntl.c',
    'setjmp.c',
    'yiyiya.c',
    'time.c',
    'signal.c',
    'timeb.c',
    'strings.c',
    'gettimeofday.c',
    'math.c',
    'getopt.c',
    'ioctl.c',
    'dirent.c',
    'assert.c',
]

if env['ARCH']=='arm':
    source=source+[
        'arm/longjmp.S',
        'arm/setjmp.S'
    ]
elif env['ARCH']=='x86':
    source=source+[
        'i386/longjmp.s',
        'i386/setjmp.s'
    ]

env.Library('c',source ,CFLAGS='$CFLAGS -Ilibs/include/c/')