# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

cflags=' -Iapp/libgui/ \
        -Iapp/libjpeg/ \
        -Iapp/libsdl2/ \
        -Iapp/libsdl2/include \
        -Iapp/libfreetype/include \
        -I. \
        -Iapp/libpng/ \
        -Iapp/libwebp/src \
        '

source=[]

source+=Glob('src/**/*.c')

source +=[

    # '../libpng/libpng.a',
    # '../libgui/libimage.a',
    # '../libgui/libgui.a',
    # '../libsdl2/libsdl2.a',
    # '../libzlib/libzlib.a',
    # '../libwebp/libwebp.a',
    ]+env['LIBC']

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Library('freetype', source,
    CFLAGS='$CFLAGS $LIBCFLAGS -DBSD -D__YIYIYA__  '+cflags,
    LINKFLAGS= '$LINKFLAGS $USER')