# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

plt=env['PLATFORM']

source=[]
source+= Glob(plt+'/*.c')
if plt:
    env['CFLAGS']= """%s -Iplatform/%s  """%(env['CFLAGS'],plt)

env.Library('platform', source)