# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

plt=env['PLATFORM']

src=[]

if plt:
    env['CFLAGS']= """%s -Iplatform/%s  """%(env['CFLAGS'],plt)
    if plt=='v3s':
        src=[
            plt+'/init.c',
            plt+'/gic.c',
            plt+'/timer.c',
        ]
        env.Library('platform', src)
    else:
        env.Library('platform', [
            plt+'/init.c',
            # plt+'/gic.c',
            # plt+'/timer.c',
            # plt+'/sys-dram.c',
            # plt+'/sys-clock.c'
            ],)