# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')



source= [
    'file.c',
    ]+env['LIBC']
    
if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


env.Program('file.elf', source,
    CFLAGS='$CFLAGS $LIBCFLAGS ',
    LINKFLAGS= '$LINKFLAGS $USER')

