# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

cflags='$CFLAGS '#-DUSE_POOL -finstrument-functions

include=[
        '../',
        '../libs/include',
        '../platform',
    ]

libs=['../arch/libarch.a',
    '../libs/libarchcommon/libarchcommon.a',
    '../libs/libalgorithm/libalgorithm.a',
    '../libs/libkernel/libkernel.a',]

env.Library('yiyiya', [
    'kernel.c',
    'thread.c',
    'schedule.c',
    'syscall.c',
    'exceptions.c',
    'memory.c',
    'module.c',
    'device.c',
    'vfs.c',
    'sysfn.c',
    'devfn.c',
    'fd.c',
    'loader.c',
    'rw_queue.c',
    'pipe.c',
    'mp.c',
   
    ],
    CPPPATH=include,
    LIBS=libs,
    CFLAGS=cflags
    )


