# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c',",om
# ********************************************************************
import os

Import('env')

source=[]

source+= [
    'allfilters.c',        
    'audio.c',             
    'avfilter.c',          
    'avfiltergraph.c',     
    'buffersink.c',        
    'buffersrc.c',         
    'drawutils.c',         
    'fifo.c',              
    'formats.c',           
    'framepool.c',         
    'graphdump.c',         
    'graphparser.c',       
    'opencl_allkernels.c', 
    'transform.c',         
    'video.c',     
]

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


source+= [
    ]+env['LIBC']

env.Library('avfilter', source,
    CFLAGS='$CFLAGS  $LIBCFLAGS -Iapp/libffmpeg/ ',)
