# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

arch_type=env['ARCHTYPE']

platform=env['PLATFORM']

driver=[]
other=[]
if arch_type =='arm':
    if platform=='v3s':
        other=[
            'gpu/v3s.c',
            'mmc/v3s.c',
            'serial/v3s.c',
            'mouse/v3s.c',
            'i2c/i2c.c',
            'i2c/v3s.c',
            'gpio/gpio.c',
            'gpio/v3s.c',
            'spi/spi.c',
            'spi/v3s.c',
        ]
    elif platform=='raspi2':
        other=[
            'gpu/bcm2836.c',
            'gpu/mailbox.c',
            'mmc/bcm2836.c',
            'mmc/bcm2835_vc.c',
            'serial/bcm2836.c',
            'mouse/bcm2836.c',
            'i2c/i2c.c',
            'i2c/bcm2836.c',
            'gpio/gpio.c',
            'gpio/bcm2836.c',
            'spi/spi.c',
            'spi/bcm2836.c',
            ]
    elif platform=='stm32f4xx':
            other=[
                'gpio/gpio.c',
                'gpio/stm32.c',
                'i2c/i2c.c',
                'i2c/stm32.c',
                'spi/spi.c',
                'spi/stm32.c',
                'lcd/lcd.c',
                'lcd/st7735.c',
                'serial/stm32.c',
                ]
    driver=[
        'fat/fat.c',
        'fat/byteordering.c',
        'fat/partition.c',
        'fat/mod.c',
        # 'fat32/fat32.c',
        
        'gpu/gpu.c',
        'mmc/sdhci.c',
        'hello/hello.c',
        'dev/devfs.c',
        'pty/pty.c'
    ]+other

elif arch_type=='x86':
    driver=['pci.c',
    'pic/pic.c',
    'ahci/ahci.c',
    'dma/dma.c',

    'hello/hello.c',
    'serial/serial.c',
    'dev/devfs.c',
    'rtc/rtc.c',
    'pty/pty.c',
    'vga/vga.c',
    'vga/mode.c',
    'vga/qemu.c',
    'mouse/mouse.c',
    'keyboard/keyboard.c',
    'fat32/fat32.c',
    
    'fat/fat.c',
    'fat/byteordering.c',
    'fat/partition.c',
    'fat/mod.c',

    'sound/sb16.c',
    'net/net.c',
    'net/e1000.c',

    'test/test.c',
    'test/test-ahci.c',
    'test/test-fat.c',
    ]

elif arch_type=='xtensa':
     driver=[
          'hello/hello.c',
        ]

source=driver+[
    '../kernel/libyiyiya.a',
    '../arch/libarch.a',
    '../libs/libalgorithm/libalgorithm.a',
    '../libs/libkernel/libkernel.a'
    ]

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Library('driver', source,
    CFLAGS='$CFLAGS -Idrivers')