# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


driver=[]
gpu=['gpu/bcm2836.c',
        'gpu/gpu.c',
        'gpu/mailbox.c'
        ]
if env['ARCH']=='arm':
    if env['PLATFORM']=='v3s':
        gpu=['gpu/v3s.c',
            'gpu/gpu.c',]

    driver=[
        'hello/hello.c',
        'dev/devfs.c',
        'pty/pty.c'
    ]+gpu
elif env['ARCH']=='x86':
    driver=['pci.c',
    'pic.c',
    'ahci.c',
    'dma.c',

    'hello/hello.c',
    'serial/serial.c',
    'dev/devfs.c',
    'rtc/rtc.c',
    'pty/pty.c',
    'vga/vga.c',
    'vga/mode.c',
    'vga/qemu.c',
    'mouse/mouse.c',
    'keyboard/keyboard.c',
    'fat32/fat32.c',
    
    'fat/fat.c',
    'fat/byteordering.c',
    'fat/partition.c',
    'fat/mod.c',

    'sound/sb16.c',]




source=driver+[
    '../kernel/libyiyiya.a',
    '../arch/libarch.a',
    '../libs/libalgorithm/libalgorithm.a',
    '../libs/libkernel/libkernel.a'
    ]

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Library('driver', source,
    CFLAGS='$CFLAGS -Idrivers')