# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

env.Library('driver', [
    'pci.c',
    'pic.c',
    'ahci.c',
    'dma.c',

    'hello/hello.c',
    'serial/serial.c',
    'dev/devfs.c',
    'rtc/rtc.c',
    'pty/pty.c',
    'vga/vga.c',
    'vga/mode.c',
    'vga/qemu.c',
    'mouse/mouse.c',
    'keyboard/keyboard.c',
    'fat32/fat32.c',
    
    'fat/fat.c',
    'fat/byteordering.c',
    'fat/partition.c',
    'fat/mod.c',

    'sound/sb16.c',

    '../kernel/libyiyiya.a',
    '../arch/libarch.a',
    '../libs/libalgorithm/libalgorithm.a',
    '../libs/libkernel/libkernel.a'
    ],
    CFLAGS='$CFLAGS -Idrivers')