# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c',",om
# ********************************************************************
import os

Import('env')

source=[]

source+= [

       'alphablend.c',                
       'hscale_fast_bilinear.c',      
       'input.c',                     
       'options.c',                   
       'output.c',                    
       'rgb2rgb.c',                   
       'swscale.c',                   
       'swscale_unscaled.c',          
       'utils.c',                     
       'yuv2rgb.c',                   
       'slice.c',                     
       'hscale.c',                    
       'vscale.c',                    
       'gamma.c',                     
]

if env['ARCHTYPE']=='arm':
    source+= [
        'arm/swscale_unscaled.c',
    ]
elif env['ARCHTYPE']=='x86':
    source+= [
        'x86/swscale.c',
        'x86/rgb2rgb.c',
        'x86/yuv2rgb.c'
    ]
else:
    print('libswscale not support',env['ARCHTYPE'])

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


source+= [
    ]+env['LIBC']

env.Library('swscale', source,
    CFLAGS='$CFLAGS  $LIBCFLAGS -Iapp/libffmpeg/ ',)
