# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

if env['ARCH']=='arm':
    plt=env['PLATFORM']
    env.Library('arch', ['arch.c','lock.c',
        'arm/io.c',
        'arm/cpu.c',
        'arm/mm.c',
        'arm/mmu_dump.c',
        'arm/display.c',
        'arm/interrupt.c',
        '../platform/libplatform.a'
        ])
elif env['ARCH']=='x86':
    env.Library('arch', ['arch.c','lock.c',
        'x86/io.c',
        'x86/cpu.c',
        'x86/mm.c',
        'x86/display.c',
        'x86/interrupt.c',
        '../platform/libplatform.a'
        ])