# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

arch =env['ARCH']

env.Library('arch', [
    'arch.c',
    'lock.c',
    'mm.c',
    arch+'/io.c',
    arch+'/cpu.c',
    arch+'/mm.c',
    # arch+'/mmu_dump.c',
    arch+'/display.c',
    arch+'/interrupt.c',
    '../platform/libplatform.a'
    ])