# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

arch =env['ARCH']

source=[
    'arch.c',
    'lock.c',
    'mm.c',
]

source+=Glob(arch+'/*.c')

env.Library('arch', source+[
    '../libs/libarchcommon/libarchcommon.a',
    '../platform/libplatform.a'
    ],CFLAGS='$CFLAGS  -Iarch -Ilibs/include/archcommon')