# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


cflags = ' -DUSE_FILE32API -DCONFIG_BIGNUM -Iapp/quickjs '


env.Library('quickjs', [
    'quickjs.c',
    'libregexp.c',
    'libunicode.c',
    'cutils.c',
    'quickjs-libc.c',
    'libbf.c',

], CFLAGS='$CFLAGS $LIBCFLAGS '+cflags)


# ./qjsc -c -o /repl.c -m repl.js ./qjsc -fbignum -c -o /qjscalc.c qjscalc.js
source = []

source += [
    'qjsc.c',
]


libs = [
    'libquickjs.a',
    'libsdl2.a',
    'libgui.a',
    'libimage.a',
    'libpng.a',
    'libzlib.a',
]

libpath = [
    '../../eggs/libsdl2/',
    '../../eggs/libsdl2-image/',
    '../../eggs/libsdl2-ttf/',
    '../../eggs/libfreetype',

    '../../eggs/libwebp/',
]


env.Program('qjsc', source,
            LIBS=libs+env.get('LIBS'),
            LIBPATH=env.get('LIBPATH')+libpath,

            CFLAGS='$CFLAGS $LIBCFLAGS  '+cflags,
            LINKFLAGS='$LINKFLAGS $USER')


source = []

source += [
    'qjs.c',
]

if env['ARCHTYPE'] == 'arm':
    source += [
        'arm/qjscalc.c',
        'arm/repl.c'
    ]
elif env['ARCHTYPE'] == 'x86':
    source += [
        'i386/qjscalc.c',
        'i386/repl.c'
    ]


if env['ARCHTYPE'] == 'x86':
    env.Program('qjs', source,
                LIBS=libs+env.get('LIBS'),
                LIBPATH=env.get('LIBPATH')+libpath,
                CFLAGS='$CFLAGS $LIBCFLAGS '+cflags,
                LINKFLAGS='$LINKFLAGS $USER')
