# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

cflags=''

source=[]

source+=Glob('src/**/*.c')

source +=[

    # '../libpng/libpng.a',
    # '../libgui/libimage.a',
    # '../libgui/libgui.a',
    # '../libsdl2/libsdl2.a',
    # '../libzlib/libzlib.a',
    # '../libwebp/libwebp.a',
    ]

include = [
    '.',
    '../',
    '../include/c',
    '../include/',
    '../libsdl2/include',
    '../libpng',
    '../libwebp/src',
    '../libfreetype/include',

]

env.Library('freetype', source,
    CPPPATH=env.get('CPPPATH')+include,
    CFLAGS='$CFLAGS $LIBCFLAGS -DBSD -D__YIYIYA__  '+cflags,
    LINKFLAGS= '$LINKFLAGS $USER')