# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


env = env.Clone(
  w=GetOption('w'),
  ENV = os.environ,
  PATH= [os.environ['PATH'],'/opt/local/bin' ],
  )

source=[
    'lua.c',
    ]
if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


source+=['../../app/liblua/liblua.a',
        # '../libmusl/lib/libm.a',
        # '/opt/local/lib/gcc/arm-none-eabi/9.2.0/libgcc.a'

]+env['LIBC']
    
source2=[
    'luac.c',
    '../../app/liblua/liblua.a',
    ]+env['LIBC']



env.Program('lua', source,
    CFLAGS='$CFLAGS $LIBCFLAGS  -frounding-math -Iapp/liblua/src/',
    LINKFLAGS= '$LINKFLAGS $USER')

env.Program('luac', source2,
    CFLAGS='$CFLAGS $LIBCFLAGS -lgcc -Iapp/liblua/src/',
    LINKFLAGS= '$LINKFLAGS $USER')
