# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


env = env.Clone(
  w=GetOption('w'),
  ENV = os.environ,
  PATH= [os.environ['PATH'],'/opt/local/bin' ],
  )

source=[
    'lua.c',
    ]

include = [
    'src',
    'include',
    '.',
]

libs=[
    'liblua.a'
]
libpath=[
    '../../eggs/liblua/src/'
]

source2=[
    'luac.c',
    ]

source_luat=[
    'luat.c',
    ]
   

env.Program('lua', source,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=env.get('LIBPATH')+libpath,
    CPPPATH=env.get('CPPPATH')+include,
    CFLAGS='$CFLAGS $LIBCFLAGS  -frounding-math ',
    LINKFLAGS= '$LINKFLAGS $USER')

env.Program('luac', source2,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=env.get('LIBPATH')+libpath,
    CPPPATH=env.get('CPPPATH')+include,
    CFLAGS='$CFLAGS $LIBCFLAGS  ',
    LINKFLAGS= '$LINKFLAGS $USER')

env.Program('luat', source_luat,
    LIBS=libs+env.get('LIBS'),
    LIBPATH=env.get('LIBPATH')+libpath,
    CPPPATH=env.get('CPPPATH')+include,
    CFLAGS='$CFLAGS $LIBCFLAGS ',
    LINKFLAGS= '$LINKFLAGS $USER')
