# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')               

env.GenerateKernelSize('config.h',['../../init/kernel'])
env.Program('init.elf', 
    ['init.c','config.h'],
    CFLAGS='$CFLAGS -I. -Iinclude  -Iarch -std=c99 -std=gnu99 -w  ',
    LINKFLAGS= '$LINKFLAGS  ') #-Ttext 0x0500 -Wl,-section-start=.apu_boot=0x1000

env.Objcopy('init.bin','init.elf',OBJCOPYFLAGS='-j .text -O binary -S')