# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

cflags=' -Iapp/libgui/ \
        -Iapp/libjpeg \
        -Iapp/libsdl2 \
        -Iapp/libsdl2/include \
        -I. \
        -Iapp/libpng/ \
        -Iapp/libwebp/ \
                        '

source=[]

source+=Glob('src/dec/*.c')
source+=Glob('src/demux/*.c')
source+=Glob('src/dsp/*.c')
source+=Glob('src/enc/*.c')
source+=Glob('src/mux/*.c')
source+=Glob('src/utils/*.c')


source +=[
    '../libjpeg/libjpeg.a',
    '../libpng/libpng.a',
    '../libzlib/libzlib.a',
    ]+env['LIBC']

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Library('webp', source,
    CFLAGS='$CFLAGS $LIBCFLAGS -DBSD -D__YIYIYA__  '+cflags,
    LINKFLAGS= '$LINKFLAGS $USER')