# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

source=[]

source+=Glob('src/*.c')
source+=Glob('src/audio/*.c')
source+=Glob('src/audio/dummy/*.c')
# source+=Glob('src/audio/aaudio/*.c')
# source+=Glob('src/audio/openslES/*.c')
source+=Glob('src/atomic/SDL_atomic.c')
source+=Glob('src/atomic/SDL_spinlock.c')
# source+=Glob('src/core/android/*.c')
source+=Glob('src/cpuinfo/*.c')
# source+=Glob('src/dynapi/*.c')
source+=Glob('src/events/*.c')
source+=Glob('src/file/*.c')
# source+=Glob('src/haptic/*.c')
# source+=Glob('src/haptic/android/*.c')
# source+=Glob('src/hidapi/*.c')
# source+=Glob('src/hidapi/android/*.cpp')
source+=Glob('src/joystick/*.c')
source+=Glob('src/joystick/dummy/*.c')
# source+=Glob('src/joystick/hidapi/*.c')
# source+=Glob('src/joystick/virtual/*.c')
# source+=Glob('src/loadso/dlopen/*.c')
# source+=Glob('src/locale/*.c')
# source+=Glob('src/locale/android/*.c')
# source+=Glob('src/misc/*.c')
# source+=Glob('src/misc/android/*.c')
# source+=Glob('src/power/*.c')
# source+=Glob('src/power/android/*.c')
# source+=Glob('src/filesystem/android/*.c')
# source+=Glob('src/sensor/*.c')
# source+=Glob('src/sensor/android/*.c')
source+=Glob('src/render/*.c')
source+=Glob('src/render/*/*.c')
source+=Glob('src/stdlib/*.c')
source+=Glob('src/libm/*.c')
source+=Glob('src/thread/*.c')
source+=Glob('src/thread/generic/*.c')
# source+=Glob('src/thread/pthread/*.c')
source+=Glob('src/timer/*.c')
source+=Glob('src/timer/dummy/*.c')
source+=Glob('src/video/*.c')
source+=Glob('src/video/yiyiya/*.c')
source+=Glob('src/video/yuv2rgb/*.c')

source +=[
    '../libgui/libgui.a',
    '../libgui/libimage.a',
    '../libjpeg/libjpeg.a',
    '../libpng/libpng.a',
    '../libzlib/libzlib.a',
    ]+env['LIBC']

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Library('sdl2', source,
    CFLAGS='$CFLAGS $LIBCFLAGS -DBSD -D__YIYIYA__ -Iapp/libgui/ -Iapp/libjpeg -Iapp/libsdl2 -Iapp/libsdl2/include -I.',
    LINKFLAGS= '$LINKFLAGS $USER')