# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


source =[
    'K6502.c',
    'InfoNES.c',
    'InfoNES_Mapper.c',
    'InfoNES_pAPU.c',
    'InfoNES_System_YiYiYa.c',
    'joypad_input.c',
    
   
    ]

libs=[
    'libgui.a',
    'libimage.a',
    'libjpeg.a',
    'libpng.a',
    'libzlib.a',
]

env.Program('infones', source,
    LIBS=libs+env.get('LIBS'),
    CFLAGS='$CFLAGS $LIBCFLAGS',
    LINKFLAGS= '$LINKFLAGS $USER')