# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

cflags=' -Iapp/libgui/ \
        -Iapp/libjpeg/ \
        -Iapp/libsdl2/ \
        -Iapp/libsdl2/include \
        -Iapp/libfreetype/include \
        -I. \
        -Iapp/libpng/ \
        -Iapp/libwebp/src \
        -DSDL_IMAGE_USE_COMMON_BACKEND \
		-DLOAD_BMP -DLOAD_GIF -DLOAD_LBM -DLOAD_PCX -DLOAD_PNM \
		-DLOAD_SVG -DLOAD_TGA -DLOAD_XCF -DLOAD_XPM -DLOAD_XV \
		 -DLOAD_PNG -DLOAD_WEBP\
        -DLOAD_JPG'#    -DLOAD_JPG

source=[]

source+=Glob('*.c')

source +=[

    # '../libpng/libpng.a',
    # '../libgui/libimage.a',
    # '../libgui/libgui.a',
    # '../libsdl2/libsdl2.a',
    # '../libzlib/libzlib.a',
    # '../libwebp/libwebp.a',
    ]+env['LIBC']

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Library('sdl2-ttf', source,
    CFLAGS='$CFLAGS $LIBCFLAGS -DBSD -D__YIYIYA__  '+cflags,
    LINKFLAGS= '$LINKFLAGS $USER')