# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.c',",om
# ********************************************************************
import os

Import('env')

source=[]

source+=[

       'allformats.c',        
       'avio.c',              
       'aviobuf.c',           
       'cutils.c',            
       'dump.c',              
       'format.c',            
       'id3v1.c',             
       'id3v2.c',             
       'metadata.c',          
       'mux.c',               
       'options.c',           
       'os_support.c',        
       'qtpalette.c',         
       'riff.c',              
       'sdp.c',               
       'url.c',               
       'utils.c',

       
       'subfile.c',   
       'mmst.c',      
       'concat.c', 
       'bintext.c',  

    #CONFIG_XMV_DEMUXER
    'xmv.c',

       'movenc.c',
       'isom.c',
       'avc.c',
        'hevc.c',
        'movenchint.c',
        'mov_chan.c',
        'rtp.c',
        'movenccenc.c',

    'rtpenc_chain.c',
    
    #CONFIG_RIFFENC
    'riffenc.c',

    # 'sapdec.c',
]

source+=[
    '../libavcodec/libavcodec.a'
]

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))


source+= [
    ]+env['LIBC']

env.Library('avformat', source,
    CFLAGS='$CFLAGS  $LIBCFLAGS  -Iapp/libffmpeg/',)
