# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

cflags='-Iapp/libcmocka/include \
        -I. \
        '

source=[]

source+=Glob('src/*.c')

source +=[
    ]+env['LIBC']

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Library('cmocka', source,
    CFLAGS='$CFLAGS $LIBCFLAGS -DBSD -D__YIYIYA__  '+cflags,
    LINKFLAGS= '$LINKFLAGS $USER')