# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

env.Library('gui', [
    'screen.c',
    'event.c',
]+env['LIBC'],CFLAGS='$CFLAGS $LIBCFLAGS')

env.Library('image', [
    'image.c',
    'jpeg_decoder.c',
    'png_decoder.c',
    '../libjpeg/libjpeg.a',
    '../libpng/libpng.a',
]+env['LIBC'],CFLAGS='$CFLAGS $LIBCFLAGS -Iapp/libjpeg -Iapp/libpng')

# env.Objcopy('gui.elf','gui',OBJCOPYFLAGS='-S --strip-all')
#env.Objcopy('gui.dbg','gui.elf',OBJCOPYFLAGS='--only-keep-debug')