# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


libs=[
    'libjpeg.a',
    'libpng.a',
    'libalgorithm.a',
    'libc.a'
]
libpath=[
    '../libjpeg/',
    '../libpng/',
    '../../duck/libs/libalgorithm'
]
include=[
    '.',
    '../libs/include/',
    '../include/c',
    '../include/',
    '../../duck/libs/include'
]+libpath

env.Library('gui', [
    'screen.c',
    'event.c',
    ],
    LIBS=libs,
    LIBPATH=env.get('LIBPATH')+libpath,
    CPPPATH=env.get('CPPPATH')+include,
    CFLAGS='$CFLAGS ')

env.Library('image', [
    'image.c',
    'jpeg_decoder.c',
    'png_decoder.c',  
    ],
    LIBS=libs,
    LIBPATH=env.get('LIBPATH')+libpath,
    CPPPATH=env.get('CPPPATH')+include,
    CFLAGS='$CFLAGS')

# env.Objcopy('gui','gui',OBJCOPYFLAGS='-S --strip-all')
#env.Objcopy('gui.dbg','gui',OBJCOPYFLAGS='--only-keep-debug')