# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


env = env.Clone(
  w=GetOption('w'),
  ENV = os.environ,
  PATH= [os.environ['PATH'],'/opt/local/bin' ],
  )


source= [
    'test.c',
    '../../libs/libc/libc.a',
    '../../libs/libalgorithm/libalgorithm.a',
    ]

if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Program('test.elf', source,
    CFLAGS='$CFLAGS -Ilibs/include/c/ ',
    LINKFLAGS= '$LINKFLAGS $USER')

