# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


env.Program('lvgl', [
    'lvgl.c',
    'lv_demo_widgets.c',
    'assets/img_lvgl_logo.c',
    'assets/img_demo_widgets_avatar.c',
    'assets/img_clothes.c',
    


    '../liblvgl/liblvgl.a',
    '../libgui/libgui.a',
    '../libgui/libimage.a',
    '../libpng/libpng.a',
    '../../libs/libc/libc.a',
    '../../libs/libalgorithm/libalgorithm.a',

    ],
    CFLAGS='$CFLAGS -Ilibs/include/c/ -Iapp/liblvgl -Iapp/libgui/ -Iapp/libjpeg -DLV_LVGL_H_INCLUDE_SIMPLE=1',
    LINKFLAGS= '$LINKFLAGS --entry main -Tuser.ld')