# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')

source= [
    'lvgl.c',
    'lv_demo_widgets.c',
    'assets/img_lvgl_logo.c',
    'assets/img_demo_widgets_avatar.c',
    'assets/img_clothes.c',
    'lv_demo_benchmark.c',
    'assets/lv_font_montserrat_16_compr_az.c',
    'assets/img_benchmark_cogwheel_argb.c',
    'assets/lv_font_montserrat_12_compr_az.c',
    'assets/lv_font_montserrat_28_compr_az.c',
    'assets/img_benchmark_cogwheel_rgb.c',

    'assets/img_benchmark_cogwheel_indexed16.c',
    'assets/img_benchmark_cogwheel_chroma_keyed.c',
    'assets/img_benchmark_cogwheel_alpha16.c',



    '../liblvgl/liblvgl.a',
    '../libgui/libgui.a',
    '../libgui/libimage.a',
    '../libpng/libpng.a',
    ]+env['LIBC']
    
if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Program('lvgl', source,
    CFLAGS='$CFLAGS $LIBCFLAGS -Iapp/liblvgl -Iapp/libgui/ -Iapp/libjpeg -DLV_LVGL_H_INCLUDE_SIMPLE=1',
    LINKFLAGS= '$LINKFLAGS $USER')