# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os
import platform 
plt = platform.system()

Import('env')

env = env.Clone(
  w=GetOption('w'),
  ENV = os.environ,
  PATH= [os.environ['PATH'],'/opt/local/bin' ],
  )

env.Program('gui.elf', [
    'gui.c',
    'screen.c',
    '../../libs/libc/libc.a',
    ],
    CFLAGS='$CFLAGS -Ilibs/include/c/ ',
    LINKFLAGS= '$LINKFLAGS --entry main -Tuser.ld')

if plt=='Darwin':
    #if env.get('w')=='hello':
    env.Command('sh', 
        ['gui.elf' ],
        ['hdid  image/disk.img &&  cp ${SOURCES[0]} /Volumes/NO\ NAME/ && hdiutil eject /Volumes/NO\ NAME/'
    ])

