# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os
import platform 
plt = platform.system()

Import('env')

env = env.Clone(
  w=GetOption('w'),
  ENV = os.environ,
  PATH= [os.environ['PATH'],'/opt/local/bin' ],
  )

env.Library('gui', [
    'screen.c',
    '../../libs/libc/libc.a',
],CFLAGS='$CFLAGS -Ilibs/include/c/')

env.Library('image', [
    'jpeg_decoder.c',
    '../../libs/libc/libc.a',
    '../jpeg/libjpeg.a',
],CFLAGS='$CFLAGS -Ilibs/include/c/')

env.Program('gui.elf', [
    'main.c',
    'libgui.a',
    'libimage.a',
    '../jpeg/libjpeg.a',
    '../../libs/libc/libc.a',
    ],
    CFLAGS='$CFLAGS -Ilibs/include/c/',
    LINKFLAGS= '$LINKFLAGS --entry main -Tuser.ld')

# env.Objcopy('gui.elf','gui',OBJCOPYFLAGS='-S --strip-all')
#env.Objcopy('gui.dbg','gui.elf',OBJCOPYFLAGS='--only-keep-debug')