# coding:utf-8
# *******************************************************************
# * Copyright 2021-2080 evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')               


env.GenerateKernelSize('config.h',['../../init/kernel'])

env.Object('boot', ['boot_'+env['ARCH']+'.s'],ASFLAGS='')

linkflags='-nostdlib -nostartfiles -T boot/arm/link.ld'

source=[ 
    'boot.o',
    'init.c',
    'config.h'
    ]

if env['PLATFORM']=='stm32f4xx':
    linkflags='-nostdlib -nostartfiles -T boot/arm/link-stm32f4xx.ld'
    source=['init.c']


if env.get('MYLIB'):
    source.append(env.get('MYLIB'))

env.Program(target ='init.elf', source = source,
    CFLAGS='$CFLAGS -I. -Iinclude',
    LINKFLAGS= linkflags)

env.Objcopy('init.bin','init.elf',OBJCOPYFLAGS='-O binary -S --strip-debug')